# Generated by Django 3.2 on 2021-08-04 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snipetnotes',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snipets',
            name='tag',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.tag'),
        ),
        migrations.AlterField(
            model_name='snipets',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
